### ISSUE TITLE
CI/CD And Maybe Testing?

### ISSUE THREAD

**Issue by prescottprue** [opencommunitymap/communitymap-ui#32]
Hey! I'm a contributor on CV19assist and saw [the post by @dmitry-yudakov](https://github.com/CV19Assist/app/issues/109). Not exactly sure if/how the two would integrate, but I'm open to helping with this project even if they are separate.

I see that you are using Firebase and wondering if you would want me to work on setting up CI/CD for the project - I have experience doing it for a number of Firebase projects, including CV19Assist, so it should be pretty easy.

I also have quite a bit of experience working with Cypress and Firebase together (I'm the author of [cypress-firebase](https://github.com/prescottprue/cypress-firebase)), so if you are interested in UI tests or tests for any cloud function, I may also be able to help there.

Open to helping with other issues/features if you had anything in particular in mind other than the ones labeled with "help wanted"

**Comment by dmitry-yudakov** [comment]
Hey Scott,

Your help would be most welcome! Unfortunately I'm not hugely experienced with CI/CD and didn't have time to deal with it yet. It's currently configured with staging firebase project to make it easier for new members to join and deploy the dev env. Production deploy is currently done manually from my local env and it should be improved.

UI tests are probably not critical for the moment as it's still pretty raw and subject to change but they'll be very useful in future. Firebase functions are currently in [separate repo](https://github.com/opencommunitymap/communitymap-cloud-functions) and they're used as API implementation - tests for them are needed indeed.

I'd love your advice on project and DB architecture and organization as well - firestore is a bit specific and the initial structure I created seems to need improvement for working with objects (like posts, places), comments and votes. There's some description [here](https://projects.invisionapp.com/freehand/document/p3eQhjsvT) and the 3rd party integration [here](https://projects.invisionapp.com/freehand/document/ed9FRATG9) and I think I better describe it in wiki or the docs?

And really anything else you notice that needs improvement - feel free to point, advice or improve - all of it will be greatly appreciated! :)

Please let me know how I assist better.

**Comment by dmitry-yudakov** [comment]
Described the DB structure [here](https://github.com/opencommunitymap/communitymap-ui/blob/master/docs/DB.md)

**Comment by prescottprue** [comment]
Made [a PR with the start of things](https://github.com/opencommunitymap/communitymap-ui/pull/33). Let me know if you are looking for anything else for now.

I'm also open to setting up eslint + prettier so that it runs as part of committing and also checks in the CI.

I'll start looking into the DB structure a bit, is there a Firebase project with data that you could add me on?

**Comment by dmitry-yudakov** [comment]
> I'm also open to setting up eslint + prettier so that it runs as part of committing and also checks in the CI.

Yep, I'm totally up for it!
 
> I'll start looking into the DB structure a bit, is there a Firebase project with data that you could add me on?

Yes, I just need your email. Ping me on dmitry dot yudakov on gmail or in our community [slack space](https://join.slack.com/t/opencommunitymap/shared_invite/zt-e7hqo2zo-rbeP~IoF0pPkAEsa0B7lcw) or [my linkedin](https://www.linkedin.com/in/dmitryyudakov/). 

Or you could DM me in my profile in [Community Map](https://communitymap.online/) via one of the posts :)) Just make sure to tell me, as we don't yet have email notifications :)

I really appreciate your help, thanks a lot! I couldn't get to the CI PRs today, sorry, but I'll do it tomorrow. 

I guess one of the important decisions for us now is how to better integrate with 3rd party projects. We have an [API](https://github.com/opencommunitymap/communitymap-cloud-functions/blob/master/docs/API.md) that will do for a moment and a way to [embed the project](https://github.com/opencommunitymap/communitymap-ui/blob/master/README.md#embedding-into-3rd-party-site) - the latter seems a bit limiting for the moment - as styling options and interacting with it (doing something after click on object on map). I'm researching more on iframe capabilities but it seems it's just limited due to security reasons.

Another option seems SDK - maybe React components for the moment and more in future. Do you think it would create enough value and be usable enough? Do you have better ideas?
